# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Arm-Connection-App'
    subscriptionId: '0f7d897e-8881-4633-95d6-c66fcc670f59'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'LogicAppDemo01'
    location: 'East US'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/samirpramane9171/ARMPipeline-repo-New/main/azuredeploy.json'
    overrideParameters: '-projectName samir9207'
    deploymentMode: 'Incremental'
    deploymentName: 'DeploymentPipeline'